import random
                                                     #random is built-in module of python use to generate random numbers etc..
intention = 'y' 
                                                 #to check the intention of player whether he/she wants to play the game or not
 
while(intention == 'y'):
    answer = random.randint(1,100)                               #The randint() method returns an integer number selected element from the specified range.
    user_input = input('Guess a number between 1 and 100: ')     #taking a input from user (awam ki rayai zarori hai :D).
    user_input = int(user_input)                                 #Because user_input was a string variable we changed it into integer here.
    counter = 1                                                   #the game will need atleast one iteration to let the user guess the  number  correctly so the counter should be atleast 1

    while user_input != answer:                               # if the number user types is not equal to the on generated by the game(or random fucntion u can say)
        if user_input > answer:
            print('The number you entered is too large. ')
        if user_input < answer:
            print('The number you entered is too small. ')
        user_input = int(input('Guess a number between 1 and 100:'))      #we are again giving  the chance to user to guess and enter the number 
        counter = counter + 1                                            #more trials are needed to guess which is why we increase the number in counter.

    print('yayyy you got it. you tried ' + str(counter) + ' times.' )        #if the user is able to guess the number correctly in first try, then the  second while loop will not be executed. 
                                                                            #But if the user doesnt guess it right. He/she will be given chances and the counter will be incremented 
    intention = input('Wanna Play Again? ')                     #the intention variable will store the user input. if it is equals to y. then the game will start again.
                                                                #if the input is not equal to 'y'. the game will end...that means that it will not execute any loops because it is out of the scope of that program
                                                     